### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by szhu212** [szhu212/100Illusts#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

https://one-hundred-illusts.herokuapp.com/#/

**Comment by szhu212** [comment]
Updated Sign up button styling.

**Comment by ryan-mapa** [comment]
Great job!
